// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BorrarCliente(arg1) {
  return window['go']['main']['App']['BorrarCliente'](arg1);
}

export function CrearActividad(arg1, arg2) {
  return window['go']['main']['App']['CrearActividad'](arg1, arg2);
}

export function EliminarActividad(arg1) {
  return window['go']['main']['App']['EliminarActividad'](arg1);
}

export function EliminarLiquidacion(arg1) {
  return window['go']['main']['App']['EliminarLiquidacion'](arg1);
}

export function EliminarPercepcion(arg1) {
  return window['go']['main']['App']['EliminarPercepcion'](arg1);
}

export function EliminarPeriodoCoeficientes(arg1, arg2, arg3) {
  return window['go']['main']['App']['EliminarPeriodoCoeficientes'](arg1, arg2, arg3);
}

export function EliminarRetencion(arg1) {
  return window['go']['main']['App']['EliminarRetencion'](arg1);
}

export function EliminarSaldoAFavor(arg1) {
  return window['go']['main']['App']['EliminarSaldoAFavor'](arg1);
}

export function EliminarVenta(arg1) {
  return window['go']['main']['App']['EliminarVenta'](arg1);
}

export function GenerarLiquidacion(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerarLiquidacion'](arg1, arg2, arg3);
}

export function GetActividades() {
  return window['go']['main']['App']['GetActividades']();
}

export function GetAlicuotas(arg1, arg2) {
  return window['go']['main']['App']['GetAlicuotas'](arg1, arg2);
}

export function GetClientes() {
  return window['go']['main']['App']['GetClientes']();
}

export function GetCoeficientesDetalle(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCoeficientesDetalle'](arg1, arg2, arg3);
}

export function GetCoeficientesResumen(arg1, arg2) {
  return window['go']['main']['App']['GetCoeficientesResumen'](arg1, arg2);
}

export function GetDetalleLiquidacionGuardada(arg1) {
  return window['go']['main']['App']['GetDetalleLiquidacionGuardada'](arg1);
}

export function GetJurisdicciones() {
  return window['go']['main']['App']['GetJurisdicciones']();
}

export function GetLiquidacionesGuardadas(arg1) {
  return window['go']['main']['App']['GetLiquidacionesGuardadas'](arg1);
}

export function GetPercepciones(arg1) {
  return window['go']['main']['App']['GetPercepciones'](arg1);
}

export function GetRetenciones(arg1) {
  return window['go']['main']['App']['GetRetenciones'](arg1);
}

export function GetSaldosAFavor(arg1) {
  return window['go']['main']['App']['GetSaldosAFavor'](arg1);
}

export function GetVentaDetalle(arg1) {
  return window['go']['main']['App']['GetVentaDetalle'](arg1);
}

export function GetVentasPorPeriodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetVentasPorPeriodo'](arg1, arg2, arg3);
}

export function GuardarAlicuotas(arg1, arg2, arg3) {
  return window['go']['main']['App']['GuardarAlicuotas'](arg1, arg2, arg3);
}

export function GuardarCliente(arg1, arg2) {
  return window['go']['main']['App']['GuardarCliente'](arg1, arg2);
}

export function GuardarCoeficientes(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GuardarCoeficientes'](arg1, arg2, arg3, arg4, arg5);
}

export function GuardarPercepcion(arg1) {
  return window['go']['main']['App']['GuardarPercepcion'](arg1);
}

export function GuardarRetencion(arg1) {
  return window['go']['main']['App']['GuardarRetencion'](arg1);
}

export function GuardarSaldoAFavor(arg1) {
  return window['go']['main']['App']['GuardarSaldoAFavor'](arg1);
}

export function GuardarVenta(arg1) {
  return window['go']['main']['App']['GuardarVenta'](arg1);
}

export function ModificarActividad(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModificarActividad'](arg1, arg2, arg3);
}

export function ModificarPeriodoCoeficientes(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ModificarPeriodoCoeficientes'](arg1, arg2, arg3, arg4, arg5);
}
