// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BorrarCliente(arg1:number):Promise<void>;

export function CrearActividad(arg1:string,arg2:string):Promise<void>;

export function EliminarActividad(arg1:number):Promise<void>;

export function EliminarLiquidacion(arg1:number):Promise<void>;

export function EliminarPercepcion(arg1:number):Promise<void>;

export function EliminarPeriodoCoeficientes(arg1:number,arg2:number,arg3:number):Promise<void>;

export function EliminarRetencion(arg1:number):Promise<void>;

export function EliminarSaldoAFavor(arg1:number):Promise<void>;

export function EliminarVenta(arg1:number):Promise<void>;

export function GenerarLiquidacion(arg1:number,arg2:number,arg3:number):Promise<Array<models.ResultadoLiquidacion>>;

export function GetActividades():Promise<Array<models.Actividad>>;

export function GetAlicuotas(arg1:number,arg2:number):Promise<Record<number, number>>;

export function GetClientes():Promise<Array<models.Cliente>>;

export function GetCoeficientesDetalle(arg1:number,arg2:number,arg3:number):Promise<Record<number, number>>;

export function GetCoeficientesResumen(arg1:number,arg2:number):Promise<Array<models.CoeficienteResumen>>;

export function GetDetalleLiquidacionGuardada(arg1:number):Promise<Array<models.ResultadoLiquidacion>>;

export function GetJurisdicciones():Promise<Array<models.Jurisdiccion>>;

export function GetLiquidacionesGuardadas(arg1:number):Promise<Array<models.LiquidacionGuardada>>;

export function GetPercepciones(arg1:number):Promise<Array<models.Percepcion>>;

export function GetRetenciones(arg1:number):Promise<Array<models.Retencion>>;

export function GetSaldosAFavor(arg1:number):Promise<Array<models.SaldoAFavor>>;

export function GetVentaDetalle(arg1:number):Promise<models.ComprobanteFull>;

export function GetVentasPorPeriodo(arg1:number,arg2:number,arg3:number):Promise<Array<models.Comprobante>>;

export function GuardarAlicuotas(arg1:number,arg2:number,arg3:Record<number, number>):Promise<void>;

export function GuardarCliente(arg1:string,arg2:string):Promise<string>;

export function GuardarCoeficientes(arg1:number,arg2:number,arg3:number,arg4:number,arg5:Record<number, number>):Promise<void>;

export function GuardarPercepcion(arg1:models.Percepcion):Promise<void>;

export function GuardarRetencion(arg1:models.Retencion):Promise<void>;

export function GuardarSaldoAFavor(arg1:models.SaldoAFavor):Promise<void>;

export function GuardarVenta(arg1:models.ComprobanteFull):Promise<number>;

export function ModificarActividad(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ModificarPeriodoCoeficientes(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;
